# Generated by Django 3.0.4 on 2020-07-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountriesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(max_length=500, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('cases', models.CharField(max_length=100, null=True)),
                ('todayCases', models.CharField(max_length=100, null=True)),
                ('deaths', models.CharField(max_length=100, null=True)),
                ('todayDeaths', models.CharField(max_length=100, null=True)),
                ('recovered', models.CharField(max_length=100, null=True)),
                ('active', models.CharField(max_length=100, null=True)),
                ('critical', models.CharField(max_length=100, null=True)),
                ('tests', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
