# Generated by Django 3.0.4 on 2020-07-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200730_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countriesdata',
            old_name='todayCases',
            new_name='today_cases',
        ),
        migrations.RenameField(
            model_name='countriesdata',
            old_name='todayDeaths',
            new_name='today_deaths',
        ),
    ]
